<a href="https://colab.research.google.com/github/akshayxemo/data-science-lab/blob/main/final_gauss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def gauss_seidel(A, b, x0, w, max_iter, tol):
    n = len(b)
    x = x0.copy()

    for k in range(max_iter):
        for i in range(n):
            x[i] = (1 - w) * x[i] + (w / A[i, i]) * (b[i] - np.dot(A[i, :i], x[:i]) - np.dot(A[i, i+1:], x[i+1:]))
        residual = np.linalg.norm(np.dot(A, x) - b)
        if residual < tol:
            break

    return x

In [ ]:
# Define the system of equations and parameters
n = 5
A = np.diag(2 * np.ones(n)) + np.diag(-1 * np.ones(n-1), k=1) + np.diag(-1 * np.ones(n-1), k=-1)
b = np.array([-(n/4) + (i/2) for i in range(1, n+1)])
x0 = np.zeros(n)
max_iter = 1000
tol = 1e-6

In [ ]:
x_solution = gauss_seidel(A, b, x0, 0.5, max_iter, tol)
print(x_solution)

[-0.20833443  0.33333151  1.12499799  1.666665    1.45833242]


In [ ]:
relaxation_factors = [0.8, 1, 1.2, 1.7]
for w in relaxation_factors:
    x_solution = gauss_seidel(A, b, x0, w, max_iter, tol)
    print(f"Solution with w={w}:")
    print(x_solution)

Solution with w=0.8:
[-0.20833446  0.33333155  1.12499812  1.66666518  1.45833255]
Solution with w=1:
[-0.20833425  0.33333196  1.12499863  1.66666564  1.45833282]
Solution with w=1.2:
[-0.20833431  0.333332    1.12499879  1.66666585  1.45833296]
Solution with w=1.7:
[-0.20833348  0.3333332   1.12500025  1.66666732  1.45833394]


In [ ]:
# Change diagonal elements to 4
A2 = 4 * A
solution2 = gauss_seidel(A2, b, x0, 1.0, max_iter, tol)
print("Solution with diagonal elements = 4:")
print(solution2)

Solution with diagonal elements = 4:
[-0.05208356  0.08333299  0.28124966  0.41666641  0.3645832 ]


In [ ]:
# Change diagonal elements to 4
A2 = 6 * A
solution2 = gauss_seidel(A2, b, x0, 1.0, max_iter, tol)
print("Solution with diagonal elements = 4:")
print(solution2)

Solution with diagonal elements = 4:
[-0.03472237  0.05555533  0.18749977  0.27777761  0.24305547]
